export const translations = {
    en: {
        ChooseLanguage: 'Choose Language',
        Continue: 'Continue with Phone Number',
        Register: 'Register Phone Number',
        PhNo: 'Phone Number',
        RegDesc: 'A 6 digit OTP will be sent via SMS to verify your phone number',
        OTP: 'OTP',
        OTPDesc: 'An OTP has been sent to ',
        Name: 'Name',
        Crops: 'Choose Crops',
        Submit: 'Submit',
        Welcome: 'Welcome Back',
        Home: 'Home',
        News: 'News',
        Shop: 'Shop',
        Profile: 'Profile',
        PlantDoctor: 'Plant Doctor',
        MandiBhav: 'Mandi Bhav',
        Weather: 'Weather',
        Community: 'Community',
        plants: {
            apple: 'Apple',
            bellPepper: 'Bell Pepper',
            brinjal: 'Brinjal',
            cabbage: 'Cabbage',
            cherry: 'Cherry',
            coffee: 'Coffee',
            cotton: 'Cotton',
            corn: 'Corn',
            cucumber: 'Cucumber',
            grape: 'Grape',
            guava: 'Guava',
            lemon: 'Lemon',
            mango: 'Mango',
            okra: 'Okra',
            onion: 'Onion',
            orange: 'Orange',
            peach: 'Peach',
            potato: 'Potato',
            rice: 'Rice',
            spinach: 'Spinach',
            strawberry: 'Strawberry',
            sugarcane: 'Sugarcane',
            tea: 'Tea',
            tomato: 'Tomato',
            wheat: 'Wheat',
        }
        
    },
    hi: { // Hindi
        ChooseLanguage: 'भाषा चुनें',
        Continue: 'फोन नंबर के साथ जारी रखें',
        Register: 'फोन नंबर रजिस्टर करें',
        PhNo: 'फोन नंबर',
        RegDesc: 'आपके फोन नंबर को सत्यापित करने के लिए 6 अंकों का ओटीपी एसएमएस के माध्यम से भेजा जाएगा',
        OTP: 'ओटीपी',
        OTPDesc: 'एक ओटीपी भेजा गया है ',
        Name: 'नाम',
        Crops: 'फसलें',
        Submit: 'सबमिट करें',
        Welcome: 'वापस स्वागत है',
        Home: 'होम',
        News: 'समाचार',
        Shop: 'दुकान',
        Profile: 'प्रोफाइल',
        PlantDoctor: 'प्लांट डॉक्टर',
        MandiBhav: 'मंडी भाव',
        Weather: 'मौसम',
        Community: 'समुदाय',
        plants: {
            apple: 'सेब',
            bellPepper: 'शिमला मिर्च',
            brinjal: 'बैंगन',
            cabbage: 'पत्ता गोभी',
            cherry: 'चेरी',
            coffee: 'कॉफी',
            cotton: 'कपास',
            corn: 'मक्का',
            cucumber: 'खीरा',
            grape: 'अंगूर',
            guava: 'अमरूद',
            lemon: 'नींबू',
            mango: 'आम',
            okra: 'भिंडी',
            onion: 'प्याज',
            orange: 'संतरा',
            peach: 'आड़ू',
            potato: 'आलू',
            rice: 'चावल',
            spinach: 'पालक',
            strawberry: 'स्ट्रॉबेरी',
            sugarcane: 'गन्ना',
            tea: 'चाय',
            tomato: 'टमाटर',
            wheat: 'गेहूं',
        }
        
        
    },
    pu: { // Punjabi
        ChooseLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
        Continue: 'ਫੋਨ ਨੰਬਰ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
        Register: 'ਫੋਨ ਨੰਬਰ ਰਜਿਸਟਰ ਕਰੋ',
        PhNo: 'ਫੋਨ ਨੰਬਰ',
        RegDesc: 'ਤੁਹਾਡੇ ਫੋਨ ਨੰਬਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰਨ ਲਈ 6 ਅੰਕਾਂ ਦਾ ਓਟੀਪੀ ਐਸਐਮਐਸ ਰਾਹੀਂ ਭੇਜਿਆ ਜਾਵੇਗਾ',
        OTP: 'ਓਟੀਪੀ',
        OTPDesc: 'ਇੱਕ ਓਟੀਪੀ ਭੇਜਿਆ ਗਿਆ ਹੈ ',
        Name: 'ਨਾਮ',
        Crops: 'ਫਸਲਾਂ',
        Submit: 'ਸਬਮਿਟ ਕਰੋ',
        Welcome: 'ਵਾਪਸੀ ਸੁਆਗਤ ਹੈ',
        Home: 'ਮੁੱਖ ਪੰਨਾ',
        News: 'ਖਬਰਾਂ',
        Shop: 'ਦੁਕਾਨ',
        Profile: 'ਪ੍ਰੋਫ਼ਾਈਲ',
        PlantDoctor: 'ਪੌਦੇ ਦਾ ਡਾਕਟਰ',
        MandiBhav: 'ਮੰਡੀ ਭਾਵ',
        Weather: 'ਮੌਸਮ',
        Community: 'ਸਮੁਦਾਇ',
        plants: {
            apple: 'ਸੇਬ',
            bellPepper: 'ਸ਼ਿਮਲਾ ਮਿਰਚ',
            brinjal: 'ਬੈਗਨ',
            cabbage: 'ਗੋਭੀ',
            cherry: 'ਚੈਰੀ',
            coffee: 'ਕੌਫ਼ੀ',
            cotton: 'ਸੂਤੀ',
            corn: 'ਮੱਕੀ',
            cucumber: 'ਖੀਰਾ',
            grape: 'ਅੰਗੂਰ',
            guava: 'ਅਮਰੂਦ',
            lemon: 'ਨਿੰਬੂ',
            mango: 'ਅੰਬ',
            okra: 'ਭਿੰਡੀ',
            onion: 'ਪਿਆਜ਼',
            orange: 'ਸੰਤਰਾ',
            peach: 'ਆੜੂ',
            potato: 'ਆਲੂ',
            rice: 'ਚੌਲ',
            spinach: 'ਪਾਲਕ',
            strawberry: 'ਸਟ੍ਰਾਬੇਰੀ',
            sugarcane: 'ਗੰਨਾ',
            tea: 'ਚਾਹ',
            tomato: 'ਟਮਾਟਰ',
            wheat: 'ਗੇਹੂੰ',
        }
        
        
    },
    gu: { // Gujarati
        ChooseLanguage: 'ભાષા પસંદ કરો',
        Continue: 'ફોન નંબર સાથે ચાલુ રાખો',
        Register: 'ફોન નંબર નોંધાવો',
        PhNo: 'ફોન નંબર',
        RegDesc: 'તમારા ફોન નંબરને ચકાસવા માટે 6 આંકડાનો ઓટીપી એસએમએસ મારફતે મોકલવામાં આવશે',
        OTP: 'ઓટીપી',
        OTPDesc: 'એક ઓટીપી મોકલવામાં આવ્યો છે ',
        Name: 'નામ',
        Crops: 'ખેતરો',
        Submit: 'સબમિટ કરો',
        Welcome: 'પાછા આવકાર',
        Home: 'હોમ',
        News: 'સમાચાર',
        Shop: 'દુકાન',
        Profile: 'પ્રોફાઇલ',
        PlantDoctor: 'પ્લાન્ટ ડોકટર',
        MandiBhav: 'માર્કેટ ભાવ',
        Weather: 'હવામાન',
        Community: 'સમુદાય',
        plants: {
            apple: 'સફરજન',
            bellPepper: 'શિમલો મરચું',
            brinjal: 'રીંગણું',
            cabbage: 'કોબી',
            cherry: 'ચેરી',
            coffee: 'કોફી',
            cotton: 'કપાસ',
            corn: 'મકાઈ',
            cucumber: 'કાકડી',
            grape: 'દ્રાક્ષ',
            guava: 'જામફળ',
            lemon: 'લીંબુ',
            mango: 'કેરી',
            okra: 'ભીંડો',
            onion: 'ડુંગળી',
            orange: 'નારંગી',
            peach: 'જારબીર',
            potato: 'બટાટા',
            rice: 'ચોખા',
            spinach: 'પાલક',
            strawberry: 'સ્ટ્રોબેરી',
            sugarcane: 'ગણું',
            tea: 'ચા',
            tomato: 'ટમેટું',
            wheat: 'ઘઉં',
        }
        
        
    },
    ba: { // Bangla
        ChooseLanguage: 'ভাষা নির্বাচন করুন',
        Continue: 'ফোন নম্বর দিয়ে চালিয়ে যান',
        Register: 'ফোন নম্বর নিবন্ধন করুন',
        PhNo: 'ফোন নম্বর',
        RegDesc: 'আপনার ফোন নম্বর যাচাই করার জন্য একটি 6-সংখ্যার ওটিপি এসএমএসের মাধ্যমে পাঠানো হবে',
        OTP: 'ওটিপি',
        OTPDesc: 'একটি ওটিপি পাঠানো হয়েছে ',
        Name: 'নাম',
        Crops: 'ফসল',
        Submit: 'জমা দিন',
        Welcome: 'পুনরায় স্বাগতম',
        Home: 'হোম',
        News: 'সংবাদ',
        Shop: 'দোকান',
        Profile: 'প্রোফাইল',
        PlantDoctor: 'গাছের ডাক্তার',
        MandiBhav: 'মন্ডি ভাও',
        Weather: 'আবহাওয়া',
        Community: 'সম্প্রদায়',
        plants: {
            apple: 'আপেল',
            bellPepper: 'বেল পেপার',
            brinjal: 'বেগুন',
            cabbage: 'বাঁধাকপি',
            cherry: 'চেরি',
            coffee: 'কফি',
            cotton: 'কটন',
            corn: 'ভুট্টা',
            cucumber: 'শসা',
            grape: 'আঙুর',
            guava: 'পেয়ারা',
            lemon: 'লেবু',
            mango: 'আম',
            okra: 'ঢেঁড়স',
            onion: 'পেঁয়াজ',
            orange: 'কমলা',
            peach: 'পিচ',
            potato: 'আলু',
            rice: 'চাল',
            spinach: 'পালং শাক',
            strawberry: 'স্ট্রবেরি',
            sugarcane: 'আখ',
            tea: 'চা',
            tomato: 'টমেটো',
            wheat: 'গম',
        }
        
        
    },
    od: { // Odia
        ChooseLanguage: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
        Continue: 'ଫୋନ୍ ନମ୍ବର ସହିତ ଜାରି ରଖନ୍ତୁ',
        Register: 'ଫୋନ୍ ନମ୍ବର ରେଜିଷ୍ଟର୍ କରନ୍ତୁ',
        PhNo: 'ଫୋନ୍ ନମ୍ବର',
        RegDesc: 'ଆପଣଙ୍କର ଫୋନ୍ ନମ୍ବର ଯାଞ୍ଚ କରିବା ପାଇଁ ଏକ 6 ଅଙ୍କର ଓଟିପି ଏସଏମଏସ୍ ଦ୍ୱାରା ପଠାଯିବ',
        OTP: 'ଓଟିପି',
        OTPDesc: 'ଏକ ଓଟିପି ପଠାଯାଇଛି ',
        Name: 'ନାମ',
        Crops: 'ଛତ୍ର',
        Submit: 'ଦାଖଲ କରନ୍ତୁ',
        Welcome: 'ପୁଣିଥରେ ସ୍ୱାଗତ',
        Home: 'ହୋମ୍',
        News: 'ସମାଚାର',
        Shop: 'ଦୋକାନ',
        Profile: 'ପ୍ରୋଫାଇଲ୍',
        PlantDoctor: 'ପ୍ଲାଣ୍ଟ ଡକ୍ଟର୍',
        MandiBhav: 'ମଣ୍ଡି ଭାଅ',
        Weather: 'ଆବହାବା',
        Community: 'ସମୁଦାୟ',
        plants: {
            apple: 'ସେବ',
            bellPepper: 'ବେଲ୍ ପେପର୍',
            brinjal: 'ବାଇଗଣ',
            cabbage: 'ବନ୍ଧାକୋବି',
            cherry: 'ଚେରୀ',
            coffee: 'କଫି',
            cotton: 'କପାସ',
            corn: 'ମକା',
            cucumber: 'କାକୁଡି',
            grape: 'ଦାକ୍ଷି',
            guava: 'ପିଜୁଳି',
            lemon: 'ଲେମୁ',
            mango: 'ଆମ୍ବ',
            okra: 'ଭଣ୍ଡା',
            onion: 'ପିଆଜ',
            orange: 'କମଳା',
            peach: 'ପିଚ୍',
            potato: 'ଆଳୁ',
            rice: 'ଚାଉଳ',
            spinach: 'ପାଳଙ୍ଗ',
            strawberry: 'ସ୍ଟ୍ରବେରି',
            sugarcane: 'ଅଖ',
            tea: 'ଚା',
            tomato: 'ଟମାଟୋ',
            wheat: 'ଗହମ',
        }
        
        
    },
    ta: { // Tamil
        ChooseLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
        Continue: 'போன் எண்காட்டி தொடரவும்',
        Register: 'போன் எண் பதிவுசெய்க',
        PhNo: 'போன் எண்',
        RegDesc: 'உங்கள் போன் எண்ணை சரிபார்க்க 6 இலக்க ஓடிபி எஸ்எம்எஸ் மூலம் அனுப்பப்படும்',
        OTP: 'ஓடிபி',
        OTPDesc: 'ஒரு ஓடிபி அனுப்பப்பட்டது ',
        Name: 'பெயர்',
        Crops: 'பயிர்கள்',
        Submit: 'சமர்ப்பிக்கவும்',
        Welcome: 'மீண்டும் வருக',
        Home: 'முகப்பு',
        News: 'செய்தி',
        Shop: 'கடை',
        Profile: 'சுயவிவரம்',
        PlantDoctor: 'மருந்து மருத்துவர்',
        MandiBhav: 'மண்டி பவ்',
        Weather: 'வானிலை',
        Community: 'சமுதாயம்',
        plants: {
            apple: 'ஆப்பிள்',
            bellPepper: 'குடைமிளகாய்',
            brinjal: 'கத்திரிக்காய்',
            cabbage: 'முட்டைகோஸ்',
            cherry: 'செர்ரி',
            coffee: 'காபி',
            cotton: 'பருத்தி',
            corn: 'மக்சிக்கோல்',
            cucumber: 'வெள்ளரிக்காய்',
            grape: 'திராட்சை',
            guava: 'கொய்யா',
            lemon: 'எலுமிச்சை',
            mango: 'மாம்பழம்',
            okra: 'வெண்டைக்காய்',
            onion: 'வெங்காயம்',
            orange: 'ஆரஞ்சு',
            peach: 'பீச்',
            potato: 'உருளைக்கிழங்கு',
            rice: 'அரிசி',
            spinach: 'கீரை',
            strawberry: 'ஸ்ட்ராபெரி',
            sugarcane: 'கரும்பு',
            tea: 'தேநீர்',
            tomato: 'தக்காளி',
            wheat: 'கோதுமை',
        }
        
        
    },
    te: { // Telugu
        ChooseLanguage: 'భాషను ఎంచుకోండి',
        Continue: 'ఫోన్ నంబర్‌తో కొనసాగించండి',
        Register: 'ఫోన్ నంబర్ నమోదు చేయండి',
        PhNo: 'ఫోన్ నంబర్',
        RegDesc: 'మీ ఫోన్ నంబర్‌ను ధృవీకరించడానికి 6 అంకెల ఓటీపీ SMS ద్వారా పంపబడుతుంది',
        OTP: 'ఓటీపీ',
        OTPDesc: 'ఒక ఓటీపీ పంపబడింది ',
        Name: 'పేరు',
        Crops: 'పంటలు',
        Submit: 'సమర్పించు',
        Welcome: 'మళ్ళీ స్వాగతం',
        Home: 'హోమ్',
        News: 'వార్తలు',
        Shop: 'దుకాణం',
        Profile: 'ప్రొఫైల్',
        PlantDoctor: 'మొక్కల డాక్టర్',
        MandiBhav: 'మండి భావ్',
        Weather: 'వాతావరణం',
        Community: 'సమాజం',
        plants: {
            apple: 'ఆపిల్',
            bellPepper: 'బెల్ పెప్పర్',
            brinjal: 'వంకాయ',
            cabbage: 'క్యాబేజీ',
            cherry: 'చెర్రీ',
            coffee: 'కాఫీ',
            cotton: 'పత్తి',
            corn: 'మొక్కజొన్న',
            cucumber: 'దోసకాయ',
            grape: 'ద్రాక్ష',
            guava: 'జామ',
            lemon: 'నిమ్మకాయ',
            mango: 'మామిడి',
            okra: 'బెండకాయ',
            onion: 'ఉల్లిపాయ',
            orange: 'నారింజ',
            peach: 'పీచ్',
            potato: 'బంగాళదుంప',
            rice: 'బియ్యం',
            spinach: 'పాలకూర',
            strawberry: 'స్ట్రాబెర్రీ',
            sugarcane: 'చెరకు',
            tea: 'చాయ్',
            tomato: 'టమోటా',
            wheat: 'గోధుమ',
        }
        
        
        
    },
    ma: { // Malayalam
        ChooseLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
        Continue: 'ഫോൺ നമ്പറോടെ തുടരുക',
        Register: 'ഫോൺ നമ്പർ രജിസ്റ്റർ ചെയ്യുക',
        PhNo: 'ഫോൺ നമ്പർ',
        RegDesc: 'നിങ്ങളുടെ ഫോൺ നമ്പർ ശരിവരുത്താൻ 6 അക്കം വരുന്ന ഒരു ഒടിപി എസ്എംഎസിലൂടെ അയയ്ക്കുന്നതാണ്',
        OTP: 'ഒടിപി',
        OTPDesc: 'ഒരു ഒടിപി അയച്ചിരിക്കുന്നു ',
        Name: 'പേര്',
        Crops: 'വിളകൾ',
        Submit: 'സമർപ്പിക്കുക',
        Welcome: 'മടങ്ങി വരവുക',
        Home: 'ഹോം',
        News: 'വാർത്ത',
        Shop: 'കട',
        Profile: 'പ്രൊഫൈൽ',
        PlantDoctor: 'പ്ലാൻറ് ഡോക്ടർ',
        MandiBhav: 'മണ്ടി ഭാവ്',
        Weather: 'കാലാവസ്ഥ',
        Community: 'സമൂഹം',
        plants: {
            apple: 'ആപ്പിൾ',
            bellPepper: 'കാപ്പിസിക്കം',
            brinjal: 'വഴുതന',
            cabbage: 'മുട്ടക്കോസ്',
            cherry: 'ചെറി',
            coffee: 'കാപ്പി',
            cotton: 'കാറ്റൺ',
            corn: 'മക്ക',
            cucumber: 'വെള്ളരിക്ക',
            grape: 'മുന്തിരി',
            guava: 'പേരക്ക',
            lemon: 'നാരങ്ങ',
            mango: 'മാങ്ങ',
            okra: 'വെണ്ടക്ക',
            onion: 'സവാള',
            orange: 'ഓറഞ്ച്',
            peach: 'പീച്ച്',
            potato: 'ഉരുളക്കിഴങ്ങ്',
            rice: 'അരി',
            spinach: 'ചീര',
            strawberry: 'സ്ട്രോബെറി',
            sugarcane: 'കരിമ്പ്',
            tea: 'ചായ',
            tomato: 'തക്കാളി',
            wheat: 'ഗോതമ്പ്',
        }
        
        
    },
};
