export const backgrounds = {
    'day':{
        'Sunny': require('../assets/weather_bg/Sunny Day.jpg'),
        'Partly Cloudy': require('../assets/weather_bg/Partly Cloudy Day.jpg'),
        'Overcast': require('../assets/weather_bg/Cloudy Day.jpg'),
        'Cloudy': require('../assets/weather_bg/Cloudy Day.jpg'),
        'Light Rain': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Patchy rain possible': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Patchy freezing drizzle possible': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Patchy light drizzle': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Light Drizzle': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Freezing Drizzle': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Patchy light rain with thunder': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Moderate or heavy rain with thunder': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Heavy Rain': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Heavy Rain at times': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Light Freezing Rain': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Light Rain Shower': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Moderate or heavy rain shower': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Torrential rain shower': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Heavy Frezing Drizzle': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Pacthy light rain': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Moderate Rain': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Moderate or heavy freezing rain': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Moderate rain at times': require('../assets/weather_bg/Light Rain Day.jpg'),
        'Light Snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Heavy Snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Moderate Snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Patchy snow possible': require('../assets/weather_bg/Snow Day.jpg'),
        'Patchy sleet possible': require('../assets/weather_bg/Snow Day.jpg'),
        'Patchy light snow with thunder': require('../assets/weather_bg/Snow Day.jpg'),
        'Patchy moderate snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Light sleet showers': require('../assets/weather_bg/Snow Day.jpg'),
        'Patchy light snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Light sleet': require('../assets/weather_bg/Snow Day.jpg'),
        'Moderate or heavy sleet': require('../assets/weather_bg/Snow Day.jpg'),
        'Patchy heavy snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Moderate or heavy sleet showers': require('../assets/weather_bg/Snow Day.jpg'),
        'Light snow showers': require('../assets/weather_bg/Snow Day.jpg'),
        'Moderate or heavy snow with thunder': require('../assets/weather_bg/Snow Day.jpg'),
        'Moderate or heavy snow showers': require('../assets/weather_bg/Snow Day.jpg'),
        'Blowing snow': require('../assets/weather_bg/Snow Day.jpg'),
        'Blizzard': require('../assets/weather_bg/Snow Day.jpg'),
        'Mist': require('../assets/weather_bg/Fog Day.jpg'),
        'Fog': require('../assets/weather_bg/Fog Day.jpg'),
        'Freezing fog': require('../assets/weather_bg/Fog Day.jpg'),
        'Thundery outbreaks possible': require('../assets/weather_bg/Thunderstorm Day.jpg'),
        'Ice pellets': require('../assets/weather_bg/Hail Day.jpg'),
        'Light showers of ice pellets': require('../assets/weather_bg/Hail Day.jpg'),
        'Moderate or heavy showers of ice pellets': require('../assets/weather_bg/Hail Day.jpg'),
        },
    'night':{
        'Clear': require('../assets/weather_bg/Clear Night.jpeg'),
        'Partly Cloudy': require('../assets/weather_bg/Partly Cloudy Night.jpg'),
        'Overcast': require('../assets/weather_bg/Partly Cloudy Night.jpg'),
        'Cloudy': require('../assets/weather_bg/Partly Cloudy Night.jpg'),
        'Patchy rain possible': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Patchy freezing drizzle possible': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Patchy light rain with thunder': require('../assets/weather_bg/Thunderstorm Night.jpg'),
        'Moderate or heavy rain with thunder': require('../assets/weather_bg/Thunderstorm Night.jpg'),
        'Patchy light drizzle': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Light Rain': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Light Drizzle': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Heavy Freezing Drizzle': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Light Rain Shower': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Torrential rain shower': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Moderate or heavy rain shower': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Patchy light rain': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Light freezing rain': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Moderate or heavy freezing rain': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Freezing drizzle': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Moderate Rain': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Moderate rain at times': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Heavy Rain': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Heavy Rain at times': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Patchy sleet possible': require('../assets/weather_bg/Light Rain Night.jpg'),
        'Light Snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Patchy snow possible': require('../assets/weather_bg/Snow Night.jpg'),
        'Heavy Snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Light sleet': require('../assets/weather_bg/Snow Night.jpg'),
        'Moderate or heavy sleet': require('../assets/weather_bg/Snow Night.jpg'),
        'Light snow showers': require('../assets/weather_bg/Snow Night.jpg'),
        'Moderate or heavy snow showers': require('../assets/weather_bg/Snow Night.jpg'),
        'Moderate Snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Patchy moderate snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Patchy light snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Light sleet showers': require('../assets/weather_bg/Snow Night.jpg'),
        'Moderate or heavy sleet showers': require('../assets/weather_bg/Snow Night.jpg'),
        'Patchy heavy snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Patchy light snow with thunder': require('../assets/weather_bg/Snow Night.jpg'),
        'Moderate or heavy snow with thunder': require('../assets/weather_bg/Snow Night.jpg'),
        'Blowing snow': require('../assets/weather_bg/Snow Night.jpg'),
        'Bizzard': require('../assets/weather_bg/Snow Night.jpg'),
        'Mist': require('../assets/weather_bg/Mist Night.jpg'),
        'Fog': require('../assets/weather_bg/Fog Night.jpg'),
        'Freezing fog': require('../assets/weather_bg/Fog Night.jpg'),
        'Thundery outbreaks possible': require('../assets/weather_bg/Thunderstorm Night.jpg'),
        'Ice pellets': require('../assets/weather_bg/Hail Night.jpg'),
        'Light showers of ice pellets': require('../assets/weather_bg/Hail Night.jpg'),
        'Moderate or heavy showers of ice pellets': require('../assets/weather_bg/Hail Night.jpg'),
    }
    
};
